package com.osmb.script.masterfarmerthiever;


import com.osmb.api.item.ItemID;

public enum Seed {
    ONION_SEED(ItemID.ONION_SEED),
    CABBAGE_SEED(ItemID.CABBAGE_SEED),
    TOMATO_SEED(ItemID.TOMATO_SEED),
    SWEETCORN_SEED(ItemID.SWEETCORN_SEED),
    STRAWBERRY_SEED(ItemID.STRAWBERRY_SEED),
    WATERMELON_SEED(ItemID.WATERMELON_SEED),
    SNAPE_GRASS(ItemID.SNAPE_GRASS),
    BARLEY_SEED(ItemID.BARLEY_SEED),
    HAMMERSTONE_SEED(ItemID.HAMMERSTONE_SEED),
    ASGARNIAN_SEED(ItemID.ASGARNIAN_SEED),
    JUTE_SEED(ItemID.JUTE_SEED),
    YANILLIAN_SEED(ItemID.YANILLIAN_SEED),
    KRANDORIAN_SEED(ItemID.KRANDORIAN_SEED),
    WILDBLOOD_SEED(ItemID.WILDBLOOD_SEED),
    MARIGOLD_SEED(ItemID.MARIGOLD_SEED),
    NASTURTIUM_SEED(ItemID.NASTURTIUM_SEED),
    ROSEMARY_SEED(ItemID.ROSEMARY_SEED),
    WOAD_SEED(ItemID.WOAD_SEED),
    LIMPWURT_SEED(ItemID.LIMPWURT_SEED),
    REDBERRY_SEED(ItemID.REDBERRY_SEED),
    CADAVABERRY_SEED(ItemID.CADAVABERRY_SEED),
    DWELLBERRY_SEED(ItemID.DWELLBERRY_SEED),
    JANGERBERRY_SEED(ItemID.JANGERBERRY_SEED),
    WHITEBERRY_SEED(ItemID.WHITEBERRY_SEED),
    POISON_IVY_SEED(ItemID.POISON_IVY_SEED),
    MUSHROOM_SPORE(ItemID.MUSHROOM_SPORE),
    BELLADONNA_SEED(ItemID.BELLADONNA_SEED),
    CACTUS_SEED(ItemID.CACTUS_SEED),
    SEAWEED_SPORE(ItemID.SEAWEED_SPORE),
    POTATO_CACTUS_SEED(ItemID.POTATO_CACTUS_SEED),
    HERB_SEEDS(ItemID.GUAM_SEED);

    private final int id;

    Seed(int id) {
        this.id = id;
    }

    public int getId() {
        return id;
    }
}
